"""The fleet: planning a run's workers, leasing them slots, and merging what they report.

A fleet run has the same shape as an in-process one from the outside (a run
row, live statistics, a summary, cache provenance, correlation), and a
different shape inside: the load is generated by N worker containers that
claim slots from this control plane, wait for one shared start instant, run
their share, and post their final report with the raw histograms. This
module owns all of that, adapted from Stoker's lifecycle where the protocol
was proven on real fleets.

The parts, in the order a run meets them:

* :func:`plan` splits the scenario into worker groups (one per engine) and
  each group into per-slot shares of the load.
* :class:`FleetRun` is the per-run supervisor thread: it evicts and reads the
  cache, launches the groups through a driver, watches the leases, releases
  the fleet with T0, handles a stop, notices a worker that stopped heart-
  beating, and finishes the run when every slot is done or lost.
* :func:`claim`, :func:`mark_ready`, :func:`heartbeat` and :func:`final` are
  the request handlers' halves, fenced by lease id so a stale process can
  never speak for a slot somebody else now holds.
* :func:`merge_summaries` turns N worker summaries into one, with the
  percentiles computed once over the merged histograms.
"""

from __future__ import annotations

import asyncio
import json
import logging
import math
import secrets
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import yaml
from sqlalchemy import select

from regulator_agent.histogram import LatencyHistogram, merge_dicts
from regulator_agent.scenario import Scenario, load_scenario
from regulator_agent.smartstore import cache_state, delta as cache_delta, evict_all
from regulator_agent.splunk import SplunkClient
from regulator_agent.sut import correlate, marker_prefix_for

from .adapters import hec_config, indexer_settings, scenario_path, target_config
from .config import FleetSettings, ServerConfig, get_settings
from .crypto import mint_run_token
from .db import session_scope
from .drivers import DriverError, DriverRef, ExecutionDriver, WorkerGroup, get_driver
from .models import (
    LEASE_CLAIMED,
    LEASE_DONE,
    LEASE_FREE,
    LEASE_LOST,
    LEASE_READY,
    LEASE_RUNNING,
    LIVE_LEASE_STATES,
    Run,
    Target,
    WorkerLease,
)

log = logging.getLogger("regulator.server.fleet")

# How far ahead of "all ready" the shared start is set. Long enough for the
# last worker's next heartbeat to carry it, short enough not to matter.
RELEASE_DELAY_S = 4.0
SUPERVISE_TICK_S = 1.0
STATE_PROVISIONING = "provisioning"
STATE_RELEASING = "releasing"
STATE_RUNNING = "running"
STATE_DRAINING = "draining"
STATE_FINISHED = "finished"
PROTOCOL_VERSION = 1


class FleetError(RuntimeError):
    """The fleet could not be planned or launched."""


# ---------------------------------------------------------------------------
# Planning
# ---------------------------------------------------------------------------


@dataclass
class SlotPlan:
    slot: int
    engine: str
    share: Dict[str, Any]


@dataclass
class GroupPlan:
    engine: str
    image: str
    workers: int
    scenario_files: Dict[str, str]
    slots: List[SlotPlan] = field(default_factory=list)


def _scenario_files(directory: Path, scenario: Scenario) -> Dict[str, str]:
    files = {"scenario.yaml": (directory / "scenario.yaml").read_text(encoding="utf-8")}
    if scenario.searches is not None:
        conf = directory / scenario.searches.file
        if conf.is_file():
            files[scenario.searches.file] = conf.read_text(encoding="utf-8")
    return files


def _sub_scenario_yaml(text: str, engine: str) -> str:
    """The scenario with only the personas of one engine, for a mixed run.

    A mixed scenario becomes two worker groups on two images. Each group runs
    the same scenario file minus the other engine's personas, with the
    engine declared so lint agrees, and the same seed so the draws line up.
    """
    document = yaml.safe_load(text) or {}
    personas = []
    for persona in document.get("personas") or []:
        steps = persona.get("steps") or []
        engines = {str(step.get("engine", "api")).lower() for step in steps}
        if persona.get("steps_from"):
            engines.add("api")
        if engine in engines or not engines:
            personas.append(persona)
    document["personas"] = personas
    document["engine"] = engine
    return yaml.safe_dump(document, sort_keys=False)


def _split_evenly(total: int, workers: int) -> List[int]:
    base, remainder = divmod(int(total), workers)
    return [base + (1 if index < remainder else 0) for index in range(workers)]


def plan(run: Run, scenario: Scenario, directory: Path, settings: FleetSettings) -> List[GroupPlan]:
    """Split the run into worker groups and slots.

    One group per engine the scenario uses. Within a group the closed model's
    virtual users are dealt out as evenly as possible; the open model's
    arrival rate is divided; the schedule model's cron steps are dealt out by
    the worker itself from its slot and the worker count. An explicit worker
    count on the run overrides the density defaults.
    """
    files = _scenario_files(directory, scenario)
    engines = sorted({step.engine for step in scenario.steps}) or ["api"]
    load = scenario.load
    model = load.model
    if run.arrival_rate_per_min:
        model = "open"
    elif run.virtual_users or run.pacing_s is not None:
        model = "closed" if model != "schedule" else model

    total_vus = int(run.virtual_users or load.virtual_users or 1)
    total_rate = float(run.arrival_rate_per_min or load.arrival_rate_per_min or 0.0)
    weights = {engine: 0.0 for engine in engines}
    for persona in scenario.personas:
        persona_engines = {step.engine for step in persona.steps} or {"api"}
        for engine in persona_engines:
            weights[engine] = weights.get(engine, 0.0) + float(persona.weight) / max(1, len(persona_engines))
    weight_total = sum(weights.values()) or 1.0

    groups: List[GroupPlan] = []
    next_slot = 0
    for engine in engines:
        density = settings.browser_contexts_per_worker if engine == "browser" else settings.vus_per_worker
        vus = total_vus if len(engines) == 1 else max(1, round(total_vus * weights[engine] / weight_total))
        rate = total_rate if len(engines) == 1 else total_rate * weights[engine] / weight_total
        if run.workers and run.workers > 0:
            workers = int(run.workers) if len(engines) == 1 else max(1, round(run.workers * weights[engine] / weight_total))
        elif model == "closed":
            workers = max(1, math.ceil(vus / density))
        else:
            workers = 1
        group = GroupPlan(
            engine=engine,
            image=settings.browser_worker_image if engine == "browser" else settings.worker_image,
            workers=workers,
            scenario_files=(
                files if len(engines) == 1
                else {**files, "scenario.yaml": _sub_scenario_yaml(files["scenario.yaml"], engine)}
            ),
        )
        vu_shares = _split_evenly(vus, workers) if model == "closed" else [0] * workers
        for index in range(workers):
            share: Dict[str, Any] = {"model": model, "engine": engine}
            if model == "closed":
                share["virtual_users"] = max(1, vu_shares[index])
            elif model == "open":
                share["arrival_rate_per_min"] = round(rate / workers, 4)
            group.slots.append(SlotPlan(slot=next_slot, engine=engine, share=share))
            next_slot += 1
        groups.append(group)
    return groups


# ---------------------------------------------------------------------------
# Launch
# ---------------------------------------------------------------------------


def public_base_url(settings: ServerConfig, fleet_kind: str) -> str:
    configured = settings.fleet.public_base_url
    if configured:
        return configured.rstrip("/")
    if fleet_kind == "k8s":
        return f"http://regulator.{settings.fleet.k8s_namespace}.svc:8080"
    return "http://regulator:8080"


def launch(run_id: int, driver: Optional[ExecutionDriver] = None) -> "FleetRun":
    """Plan the run, seed its leases and start its supervisor thread.

    Raises :class:`FleetError` before anything is launched when the plan
    cannot be made; a driver failure after that is recorded on the run.
    """
    settings = get_settings()
    with session_scope() as session:
        run = session.get(Run, run_id)
        if run is None:
            raise FleetError(f"run {run_id} does not exist")
        target = session.get(Target, run.target_id) if run.target_id else None
        if target is None:
            raise FleetError("the target for this run has been deleted")
        directory, _ = scenario_path(run.scenario)
        scenario = load_scenario(directory)
        groups = plan(run, scenario, directory, settings.fleet)
        if driver is None:
            driver = get_driver(run.fleet, settings.fleet)
        if run.fleet == "swarm" and not settings.fleet.swarm_available:
            raise FleetError("the swarm fleet needs PORTAINER_HOST and PORTAINER_TOKEN on the control plane")

        # Seed a lease per slot: the roster the workers claim from.
        for existing in list(run.leases):
            session.delete(existing)
        for group in groups:
            for slot_plan in group.slots:
                session.add(
                    WorkerLease(
                        run_id=run.id,
                        slot=slot_plan.slot,
                        engine=slot_plan.engine,
                        state=LEASE_FREE,
                        share_json={**slot_plan.share, "group": group.engine},
                    )
                )
        run.workers = sum(group.workers for group in groups)
        run.fleet_state = STATE_PROVISIONING
        run.state = "pending"
        run.t0 = None
        session.add(run)
        run_number = run.id

    supervisor = FleetRun(run_number, groups, driver)
    supervisor.start()
    return supervisor


# ---------------------------------------------------------------------------
# The request handlers' halves
# ---------------------------------------------------------------------------


def _leases(session, run: Run) -> List[WorkerLease]:
    return list(
        session.scalars(select(WorkerLease).where(WorkerLease.run_id == run.id).order_by(WorkerLease.slot))
    )


def _find(session, run: Run, slot: int) -> Optional[WorkerLease]:
    return session.scalar(select(WorkerLease).where(WorkerLease.run_id == run.id, WorkerLease.slot == slot))


def _holder_ok(lease: Optional[WorkerLease], lease_id: Optional[str]) -> bool:
    return lease is not None and bool(lease_id) and lease.lease_id == lease_id


def _claim_env(run: Run, target: Target, settings: ServerConfig, share: Dict[str, Any]) -> Dict[str, str]:
    """The standalone environment a worker would have had, from the run row.

    The worker parses this with the same code and validations as a standalone
    run, so there is one way for a value to be wrong.
    """
    cfg = target_config(target)
    env: Dict[str, str] = {
        "REG_TARGET_URL": cfg.url,
        "REG_TARGET_VERIFY_TLS": "1" if cfg.verify_tls else "0",
        "REG_TARGET_APP": cfg.app,
        "REG_TARGET_OWNER": cfg.owner,
        "REG_TARGET_API_VERSION": cfg.api_version,
        "REG_LINT_STRICT": "1",
        # The control plane evicts and reads the cache; workers never touch it.
        "REG_EVICT_CACHE": "0",
    }
    if cfg.web_url:
        env["REG_TARGET_WEB_URL"] = cfg.web_url
    if cfg.token:
        env["REG_TARGET_TOKEN"] = cfg.token
    if cfg.username and cfg.password:
        env["REG_TARGET_USERNAME"] = cfg.username
        env["REG_TARGET_PASSWORD"] = cfg.password
    hec = hec_config(settings)
    if hec is not None:
        env["REG_HEC_URL"] = hec.url
        env["REG_HEC_TOKEN"] = hec.token
        env["REG_HEC_VERIFY_TLS"] = "1" if hec.verify_tls else "0"
        if hec.index:
            env["REG_HEC_INDEX"] = hec.index
    if share.get("model") == "closed" and share.get("virtual_users"):
        env["REG_VUS"] = str(int(share["virtual_users"]))
    if share.get("model") == "open" and share.get("arrival_rate_per_min"):
        env["REG_ARRIVAL_RATE_PER_MIN"] = str(share["arrival_rate_per_min"])
    if run.duration_s:
        env["REG_DURATION_S"] = str(run.duration_s)
    if run.pacing_s is not None:
        env["REG_PACING_S"] = str(run.pacing_s)
    if run.seed:
        env["REG_SEED"] = str(run.seed)
    return env


def claim(session, run: Run, holder: str, hint_slot: Optional[int], files_by_engine: Dict[str, Dict[str, str]]) -> Dict[str, Any]:
    """Issue a lease. Fenced with a fresh lease id every time it changes hands."""
    from fastapi import HTTPException

    if run.fleet_state in (STATE_DRAINING, STATE_FINISHED) or run.state in ("completed", "stopped", "aborted", "failed"):
        raise HTTPException(status_code=409, detail="the run is not accepting claims")
    leases = _leases(session, run)
    # Idempotent for a holder that already has a live lease: a retried claim
    # after a dropped response must not take a second slot.
    for lease in leases:
        if lease.holder == holder and lease.state in LIVE_LEASE_STATES:
            lease.last_heartbeat_at = time.time()
            return _claim_response(session, run, lease, files_by_engine)
    claimable = [lease for lease in leases if lease.state in (LEASE_FREE, LEASE_LOST)]
    if not claimable:
        raise HTTPException(status_code=409, detail="no free lease: every slot is held")
    chosen = None
    if hint_slot is not None:
        chosen = next((lease for lease in claimable if lease.slot == hint_slot), None)
    if chosen is None:
        chosen = claimable[0]
    if chosen.state == LEASE_LOST:
        chosen.restarts = (chosen.restarts or 0) + 1
    chosen.lease_id = secrets.token_urlsafe(16)
    chosen.holder = holder
    chosen.state = LEASE_CLAIMED
    chosen.claimed_at = time.time()
    chosen.last_heartbeat_at = time.time()
    session.add(chosen)
    session.flush()
    return _claim_response(session, run, chosen, files_by_engine)


def _claim_response(session, run: Run, lease: WorkerLease, files_by_engine: Dict[str, Dict[str, str]]) -> Dict[str, Any]:
    settings = get_settings()
    target = session.get(Target, run.target_id)
    share = dict(lease.share_json or {})
    files = files_by_engine.get(lease.engine) or next(iter(files_by_engine.values()), {})
    return {
        "slot": lease.slot,
        "lease_id": lease.lease_id,
        "total_workers": int(run.workers or 1),
        "engine": lease.engine,
        "run_label": f"r{run.id}" + (f"-{run.label}" if run.label else ""),
        "scenario": {"name": run.scenario, "files": files},
        "env": _claim_env(run, target, settings, share),
        "share": share,
        "heartbeat_s": settings.fleet.heartbeat_s,
        "lease_s": settings.fleet.lease_s,
        "t0": run.t0,
    }


def mark_ready(session, run: Run, slot: int, lease_id: Optional[str]) -> None:
    from fastapi import HTTPException

    lease = _find(session, run, slot)
    if not _holder_ok(lease, lease_id):
        raise HTTPException(status_code=409, detail="lease is not the slot holder (superseded)")
    assert lease is not None
    lease.last_heartbeat_at = time.time()
    if lease.state in (LEASE_CLAIMED, LEASE_READY):
        lease.state = LEASE_READY
    session.add(lease)
    session.flush()
    evaluate_release(session, run)


def evaluate_release(session, run: Run, force: bool = False) -> bool:
    """Set T0 once every live lease is ready, or when forced by the timeout."""
    if run.t0 is not None or run.fleet_state not in (STATE_PROVISIONING, None):
        return False
    leases = _leases(session, run)
    ready = [lease for lease in leases if lease.state == LEASE_READY]
    pending = [lease for lease in leases if lease.state in (LEASE_FREE, LEASE_CLAIMED)]
    if not ready:
        return False
    if pending and not force:
        return False
    if pending:
        for lease in pending:
            lease.state = LEASE_LOST
            session.add(lease)
    run.t0 = time.time() + RELEASE_DELAY_S
    run.fleet_state = STATE_RELEASING
    session.add(run)
    log.info("run %s released: T0 in %.0fs, %d worker(s) ready, %d lost", run.id, RELEASE_DELAY_S, len(ready), len(pending))
    return True


def heartbeat(session, run: Run, slot: int, lease_id: Optional[str], payload: Dict[str, Any]) -> Dict[str, Any]:
    """Renew the lease, keep its live statistics, and answer with a command."""
    lease = _find(session, run, slot)
    if not _holder_ok(lease, lease_id):
        return {"command": "superseded"}
    assert lease is not None
    now = time.time()
    lease.last_heartbeat_at = now
    stats = payload.get("stats")
    if isinstance(stats, dict):
        lease.stats_json = stats
    reported = str(payload.get("state") or "")
    if run.fleet_state == STATE_DRAINING or run.state in ("stopped", "aborted", "failed", "completed"):
        session.add(lease)
        return {"command": "stop"}
    if lease.state == LEASE_LOST:
        lease.state = LEASE_RUNNING if run.t0 is not None else LEASE_READY
    if run.t0 is not None and lease.state in (LEASE_CLAIMED, LEASE_READY):
        if reported != "running":
            # Not yet started: tell it T0 again. Repeating the release until
            # the worker says it is running is what makes a heartbeat lost
            # in transit harmless.
            session.add(lease)
            return {"command": "release", "t0": run.t0}
        lease.state = LEASE_RUNNING
        if run.fleet_state == STATE_RELEASING:
            run.fleet_state = STATE_RUNNING
            run.state = "running"
            run.started_at = run.started_at or run.t0
            session.add(run)
    session.add(lease)
    return {"command": "continue"}


def final(session, run: Run, slot: int, lease_id: Optional[str], summary: Dict[str, Any], log_tail: List[str]) -> None:
    """Record a worker's final report. A superseded worker's report is ignored."""
    lease = _find(session, run, slot)
    if lease is None:
        return
    if lease_id and lease.lease_id != lease_id:
        log.info("run %s slot %s: final from a superseded lease ignored", run.id, slot)
        return
    if lease.state != LEASE_DONE:
        lease.summary_json = summary
        lease.log_tail_json = list(log_tail or [])[-200:]
        lease.state = LEASE_DONE
        lease.last_heartbeat_at = time.time()
        session.add(lease)


# ---------------------------------------------------------------------------
# Merging
# ---------------------------------------------------------------------------


def _hist(documents: Sequence[Optional[Dict[str, Any]]]) -> LatencyHistogram:
    return merge_dicts([doc for doc in documents if isinstance(doc, dict)])


def merge_summaries(run_label: str, scenario: str, summaries: Sequence[Dict[str, Any]], lost_slots: Sequence[int]) -> Dict[str, Any]:
    """One summary from many, with the percentiles computed over the merged histograms.

    Counts add. Histograms add. Peaks add (an upper bound on the fleet's true
    peak, stated as such). Percentiles are never averaged: that was the whole
    reason the workers ship buckets rather than numbers.
    """
    summaries = [s for s in summaries if isinstance(s, dict)]
    stats_list = [s.get("stats") or {} for s in summaries]
    hists = [st.get("histograms") or {} for st in stats_list]

    def total(key: str) -> int:
        return int(sum(int(st.get(key) or 0) for st in stats_list))

    started = min((float(s.get("started_at") or 0) for s in summaries if s.get("started_at")), default=time.time())
    ended = max((float(s.get("ended_at") or 0) for s in summaries if s.get("ended_at")), default=time.time())
    duration = max(0.0, ended - started)
    executions = total("executions")
    errors = total("errors")

    errors_by_class: Dict[str, int] = {}
    for st in stats_list:
        for key, value in (st.get("errors_by_class") or {}).items():
            errors_by_class[key] = errors_by_class.get(key, 0) + int(value or 0)

    latency = _hist([h.get("latency") for h in hists])
    failure = _hist([h.get("failure_latency") for h in hists])
    queued = _hist([h.get("queued") for h in hists])
    loop_lag = _hist([h.get("loop_lag") for h in hists])
    drift = _hist([h.get("drift") for h in hists])

    # Steps, merged by id.
    merged_steps: Dict[str, Dict[str, Any]] = {}
    step_hists: Dict[str, List[Dict[str, Any]]] = {}
    for st, h in zip(stats_list, hists):
        for step in st.get("steps") or []:
            sid = str(step.get("step_id"))
            entry = merged_steps.setdefault(
                sid,
                {"step_id": sid, "class": step.get("class", "unclassified"), "executions": 0, "successes": 0,
                 "partial": 0, "errors": 0, "errors_by_class": {}, "scan_count_total": 0,
                 "result_count_total": 0, "_run_duration_total_s": 0.0},
            )
            for key in ("executions", "successes", "partial", "errors", "scan_count_total", "result_count_total"):
                entry[key] += int(step.get(key) or 0)
            for key, value in (step.get("errors_by_class") or {}).items():
                entry["errors_by_class"][key] = entry["errors_by_class"].get(key, 0) + int(value or 0)
            # The per-search mean carries the duration total back out.
            mean_eps = step.get("mean_events_per_s")
            if mean_eps and step.get("scan_count_total"):
                entry["_run_duration_total_s"] += float(step["scan_count_total"]) / float(mean_eps)
            step_hists.setdefault(sid, []).append((h.get("steps") or {}).get(sid) or {})
    steps_out: List[Dict[str, Any]] = []
    for sid, entry in merged_steps.items():
        parts = step_hists.get(sid, [])
        entry["latency"] = _hist([p.get("latency") for p in parts]).summary()
        entry["failure_latency"] = _hist([p.get("failure_latency") for p in parts]).summary()
        entry["service_time"] = _hist([p.get("service_time") for p in parts]).summary()
        entry["dispatch"] = _hist([p.get("dispatch") for p in parts]).summary()
        entry["ttfr"] = _hist([p.get("ttfr") for p in parts]).summary()
        entry["error_rate_pct"] = round(100.0 * entry["errors"] / entry["executions"], 3) if entry["executions"] else 0.0
        entry["scan_count_per_search"] = (
            round(entry["scan_count_total"] / entry["successes"], 1) if entry["successes"] else None
        )
        duration_total = entry.pop("_run_duration_total_s")
        entry["mean_events_per_s"] = round(entry["scan_count_total"] / duration_total, 1) if duration_total else None
        steps_out.append(entry)

    job_executions = total("job_executions") or sum(
        int((st.get("queueing") or {}).get("job_executions") or 0) for st in stats_list
    )
    searches_queued = sum(int((st.get("queueing") or {}).get("searches_queued") or 0) for st in stats_list)
    peak_in_flight = sum(int(st.get("peak_in_flight") or 0) for st in stats_list)
    max_loop_lag = max((float((st.get("generator") or {}).get("max_loop_lag_ms") or 0) for st in stats_list), default=0.0)
    max_debt = max((float((st.get("generator") or {}).get("max_schedule_debt_ms") or 0) for st in stats_list), default=0.0)

    stats = {
        "run_id": run_label,
        "slot": 0,
        "elapsed_s": round(duration, 2),
        "executions": executions,
        "successes": executions - errors,
        "iterations_completed": total("iterations_completed"),
        "errors": errors,
        "error_rate_pct": round(100.0 * errors / executions, 3) if executions else 0.0,
        "errors_by_class": errors_by_class,
        "partial": total("partial"),
        "abandoned": total("abandoned"),
        "in_flight": 0,
        # A sum of per-worker peaks: an upper bound on the fleet's true peak,
        # since the workers' peaks need not have coincided.
        "peak_in_flight": peak_in_flight,
        "peak_in_flight_note": "sum of the workers' peaks, an upper bound",
        "throughput_per_s": round(executions / duration, 2) if duration > 0 else 0.0,
        "latency": latency.summary(),
        "failure_latency": failure.summary(),
        "queueing": {
            "searches_queued": searches_queued,
            "job_executions": job_executions,
            "queued_pct": round(100.0 * searches_queued / job_executions, 2) if job_executions else 0.0,
            "queued_ms": queued.summary(),
        },
        "generator": {
            "max_loop_lag_ms": round(max_loop_lag, 1),
            "loop_lag_p95_ms": round(loop_lag.percentile_ms(95), 1) if len(loop_lag) else 0.0,
            "max_schedule_debt_ms": round(max_debt, 1),
            "schedule_debt_p95_ms": round(drift.percentile_ms(95), 1) if len(drift) else 0.0,
            "max_drift_ms": round(max_debt, 1),
        },
        "steps": steps_out,
        "arrivals_missed": total("arrivals_missed"),
        "arrivals_shed": total("arrivals_shed"),
        "arrivals_skipped": total("arrivals_skipped"),
        "workers": len(summaries),
    }
    first = summaries[0] if summaries else {}
    target = (first.get("stats") or {}).get("target")
    if target:
        stats["target"] = target

    outcomes = [str(s.get("outcome") or "failed") for s in summaries]
    if "failed" in outcomes:
        outcome = "failed"
    elif "aborted" in outcomes:
        outcome = "aborted"
    elif "stopped" in outcomes:
        outcome = "stopped"
    else:
        outcome = "completed"
    reasons = [str(s.get("invalid_reason")) for s in summaries if s.get("invalid_reason")]
    valid = all(bool(s.get("valid")) for s in summaries) and not lost_slots and bool(summaries)
    if lost_slots:
        reasons.append(
            f"{len(lost_slots)} worker(s) were lost (slots {', '.join(str(s) for s in lost_slots)}): "
            "their share of the load was never applied, so this is not the configured workload"
        )
    if not summaries:
        reasons.append("no worker reported a result")

    configured = dict(first.get("configured_load") or {})
    configured["workers"] = len(summaries) + len(lost_slots)
    per_worker = [s.get("configured_load") or {} for s in summaries]
    if configured.get("model") == "closed":
        configured["virtual_users"] = sum(int(p.get("virtual_users") or 0) for p in per_worker)
    elif configured.get("model") == "open":
        configured["arrival_rate_per_min"] = round(sum(float(p.get("arrival_rate_per_min") or 0) for p in per_worker), 3)
    configured.pop("slot", None)

    return {
        "run_id": run_label,
        "slot": 0,
        "scenario": scenario,
        "outcome": outcome,
        "valid": valid,
        "invalid_reason": "; ".join(reasons) or None,
        "started_at": started,
        "ended_at": ended,
        "duration_s": round(duration, 3),
        "target_url": first.get("target_url"),
        "self_instrumented": any(bool(s.get("self_instrumented")) for s in summaries),
        "co_corrected": all(bool(s.get("co_corrected")) for s in summaries) if summaries else False,
        "load_model": first.get("load_model"),
        "peak_virtual_users": sum(int(s.get("peak_virtual_users") or 0) for s in summaries),
        "stats": stats,
        "cache": None,
        "sut": None,
        "abort_reason": next((s.get("abort_reason") for s in summaries if s.get("abort_reason")), None),
        "scenario_seed": first.get("scenario_seed", 0),
        "effective_seed": first.get("effective_seed", first.get("scenario_seed", 0)),
        "scenario_digest": first.get("scenario_digest"),
        "configured_load": configured,
        "agent_version": first.get("agent_version", ""),
        "workers": [
            {
                "slot": int((s.get("stats") or {}).get("slot") or s.get("slot") or 0),
                "outcome": s.get("outcome"),
                "valid": s.get("valid"),
                "executions": int((s.get("stats") or {}).get("executions") or 0),
                "errors": int((s.get("stats") or {}).get("errors") or 0),
                "p95_ms": ((s.get("stats") or {}).get("latency") or {}).get("p95_ms"),
            }
            for s in summaries
        ] + [{"slot": slot, "outcome": "lost", "valid": False, "executions": 0, "errors": 0, "p95_ms": None} for slot in lost_slots],
    }


def live_snapshot(run: Run, leases: Sequence[WorkerLease]) -> Dict[str, Any]:
    """A fleet's live aggregate from its workers' last heartbeats.

    Counts add; percentiles are those of the largest contributor, labelled as
    such, because a heartbeat carries summaries rather than buckets and the
    honest merge waits for the final reports.
    """
    stats_list = [lease.stats_json for lease in leases if isinstance(lease.stats_json, dict)]
    executions = sum(int(st.get("executions") or 0) for st in stats_list)
    errors = sum(int(st.get("errors") or 0) for st in stats_list)
    biggest = max(stats_list, key=lambda st: int(st.get("executions") or 0), default={})
    elapsed = max((float(st.get("elapsed_s") or 0) for st in stats_list), default=0.0)
    return {
        "run_id": f"r{run.id}",
        "elapsed_s": round(elapsed, 2),
        "executions": executions,
        "errors": errors,
        "error_rate_pct": round(100.0 * errors / executions, 3) if executions else 0.0,
        "in_flight": sum(int(st.get("in_flight") or 0) for st in stats_list),
        "peak_in_flight": sum(int(st.get("peak_in_flight") or 0) for st in stats_list),
        "throughput_per_s": round(sum(float(st.get("throughput_per_s") or 0) for st in stats_list), 2),
        "latency": biggest.get("latency") or LatencyHistogram().summary(),
        "latency_note": "live percentiles are the busiest worker's; the merged figures arrive with the final reports",
        "queueing": {
            "searches_queued": sum(int((st.get("queueing") or {}).get("searches_queued") or 0) for st in stats_list),
            "queued_pct": (biggest.get("queueing") or {}).get("queued_pct", 0.0),
            "queued_ms": (biggest.get("queueing") or {}).get("queued_ms") or LatencyHistogram().summary(),
        },
        "generator": biggest.get("generator") or {},
        "steps": [],
        "workers": [
            {
                "slot": lease.slot,
                "engine": lease.engine,
                "state": lease.state,
                "holder": lease.holder,
                "executions": int((lease.stats_json or {}).get("executions") or 0),
                "errors": int((lease.stats_json or {}).get("errors") or 0),
                "p95_ms": ((lease.stats_json or {}).get("latency") or {}).get("p95_ms"),
                "last_heartbeat_at": lease.last_heartbeat_at,
                "restarts": lease.restarts,
            }
            for lease in leases
        ],
        "fleet_state": run.fleet_state,
        "t0": run.t0,
    }


# ---------------------------------------------------------------------------
# The per-run supervisor
# ---------------------------------------------------------------------------


class FleetRun(threading.Thread):
    """One thread per fleet run: launch, watch, release, finish."""

    def __init__(self, run_id: int, groups: List[GroupPlan], driver: ExecutionDriver) -> None:
        super().__init__(name=f"regulator-fleet-{run_id}", daemon=True)
        self.run_id = run_id
        self.groups = groups
        self.driver = driver
        self.files_by_engine: Dict[str, Dict[str, str]] = {g.engine: g.scenario_files for g in groups}
        self.refs: List[DriverRef] = []
        self.stop_requested = False
        self._stopped_driver = False

    def request_stop(self) -> None:
        self.stop_requested = True
        with session_scope() as session:
            run = session.get(Run, self.run_id)
            if run is not None and run.fleet_state not in (STATE_FINISHED,):
                run.fleet_state = STATE_DRAINING
                session.add(run)

    # ------------------------------------------------------------------

    def run(self) -> None:  # noqa: D102 - Thread API
        try:
            asyncio.run(self._supervise())
        except Exception as exc:  # noqa: BLE001 - recorded on the run, never lost
            log.exception("fleet run %s failed", self.run_id)
            self._finish_failed(f"the fleet supervisor failed: {exc}")
        finally:
            self._destroy_quietly()
            from .runner import manager

            manager.forget(self.run_id)

    async def _supervise(self) -> None:
        settings = get_settings()
        with session_scope() as session:
            run = session.get(Run, self.run_id)
            target = session.get(Target, run.target_id)
            cfg = target_config(target)
            where = indexer_settings(target)
            evict_indexes = (run.evict_cache_indexes or "").split(",") if run.evict_cache_indexes else []
            evict = bool(run.evict_cache)
            corpus_index = None
            duration = float(run.duration_s or 0)
            label = f"r{run.id}" + (f"-{run.label}" if run.label else "")
        try:
            directory, _ = scenario_path(self._scenario_name())
            scenario = load_scenario(directory)
            corpus_index = scenario.corpus.index
            if not duration:
                duration = float(scenario.load.duration_s or 0)
        except Exception:  # noqa: BLE001 - the plan already loaded it once
            pass

        client = SplunkClient(cfg)
        await client.start()
        eviction = None
        before = None
        try:
            if evict:
                indexes = None if "*" in evict_indexes else (evict_indexes or ([corpus_index] if corpus_index else None))
                eviction = await evict_all(client, indexes=indexes, **where)
            before = await cache_state(client, **where)

            # Launch every group. The bootstrap is the same for all of them.
            token = mint_run_token(self.run_id)
            base_url = public_base_url(settings, self.driver.kind if self.driver.kind != "fake" else "swarm")
            slot_base = 0
            for group in self.groups:
                worker_group = WorkerGroup(
                    run_id=self.run_id,
                    group=group.engine,
                    image=group.image,
                    workers=group.workers,
                    env={
                        "REG_RUN_ID": str(self.run_id),
                        "REG_CONTROL_URL": base_url,
                        "REG_RUN_JWT": token,
                        "REG_LOG_LEVEL": "INFO",
                    },
                    labels={"regulator.scenario": self._scenario_name()},
                    stop_grace_s=90,
                    options={"slot_base": slot_base, "active_deadline_s": int(duration + 600) if duration else None},
                )
                slot_base += group.workers
                try:
                    ref = self.driver.create(worker_group)
                except DriverError as exc:
                    raise FleetError(f"could not launch the {group.engine} workers: {exc}") from exc
                self.refs.append(ref)
            with session_scope() as session:
                run = session.get(Run, self.run_id)
                run.driver_refs_json = [ref.to_json() for ref in self.refs]
                session.add(run)

            await self._watch(settings, duration)

            # Every slot is done or lost: merge, then the cluster's own view.
            with session_scope() as session:
                run = session.get(Run, self.run_id)
                leases = _leases(session, run)
                summaries = [lease.summary_json for lease in leases if lease.state == LEASE_DONE and lease.summary_json]
                lost = [lease.slot for lease in leases if lease.state == LEASE_LOST]
                scenario_name = run.scenario
            merged = merge_summaries(label, scenario_name, summaries, lost)
            if before is not None and before.available:
                after = await cache_state(client, **where)
                merged["cache"] = {"before": before.to_dict(), "after": after.to_dict(), "delta": cache_delta(before, after).to_dict()}
                if eviction is not None:
                    merged["cache"]["eviction"] = eviction.to_dict()
            elif before is not None:
                merged["cache"] = {"available": False, "reason": before.reason}
            if merged.get("started_at") and merged.get("ended_at") and summaries:
                try:
                    merged["sut"] = await correlate(client, merged["started_at"], merged["ended_at"], marker_prefix_for(label))
                except Exception as exc:  # noqa: BLE001 - correlation never fails a run
                    log.warning("correlation failed for run %s: %s", self.run_id, exc)
            with session_scope() as session:
                run = session.get(Run, self.run_id)
                run.summary_json = merged
                run.stats_json = merged.get("stats")
                run.state = merged["outcome"] if summaries else "failed"
                if not summaries and not run.error:
                    run.error = merged.get("invalid_reason") or "no worker reported a result"
                run.ended_at = time.time()
                run.fleet_state = STATE_FINISHED
                session.add(run)
        finally:
            await client.close()

    async def _watch(self, settings: ServerConfig, duration: float) -> None:
        """Until every lease is done or lost."""
        provision_deadline = time.time() + settings.fleet.provision_timeout_s
        lease_s = settings.fleet.lease_s
        hard_deadline: Optional[float] = None
        while True:
            await asyncio.sleep(SUPERVISE_TICK_S)
            with session_scope() as session:
                run = session.get(Run, self.run_id)
                leases = _leases(session, run)
                now = time.time()

                # A worker that stopped heartbeating loses its lease.
                for lease in leases:
                    if lease.state in LIVE_LEASE_STATES and lease.last_heartbeat_at and now - lease.last_heartbeat_at > lease_s:
                        log.warning("run %s slot %s lost: no heartbeat for %.0fs", run.id, lease.slot, now - lease.last_heartbeat_at)
                        lease.state = LEASE_LOST
                        session.add(lease)

                if run.t0 is None and run.fleet_state == STATE_PROVISIONING and now > provision_deadline:
                    if not evaluate_release(session, run, force=True):
                        for lease in leases:
                            if lease.state in (LEASE_FREE, LEASE_CLAIMED):
                                lease.state = LEASE_LOST
                                session.add(lease)
                        run.error = "no worker became ready within the provisioning timeout"
                        run.fleet_state = STATE_DRAINING
                        session.add(run)

                if run.t0 is not None and hard_deadline is None:
                    hard_deadline = run.t0 + (duration or 0) + 300.0

                states = [lease.state for lease in leases]
                if all(state in (LEASE_DONE, LEASE_LOST) for state in states):
                    return
                if hard_deadline is not None and now > hard_deadline:
                    for lease in leases:
                        if lease.state not in (LEASE_DONE,):
                            lease.state = LEASE_LOST
                            session.add(lease)
                    return
                if run.fleet_state == STATE_DRAINING and not self._stopped_driver:
                    self._stopped_driver = True
                    for ref in self.refs:
                        try:
                            self.driver.stop(ref, grace_s=90)
                        except DriverError as exc:
                            log.warning("stopping %s failed: %s", ref.id, exc)

    def _scenario_name(self) -> str:
        with session_scope() as session:
            run = session.get(Run, self.run_id)
            return run.scenario if run else ""

    def _finish_failed(self, error: str) -> None:
        with session_scope() as session:
            run = session.get(Run, self.run_id)
            if run is None:
                return
            run.state = "failed"
            run.error = error
            run.ended_at = time.time()
            run.fleet_state = STATE_FINISHED
            session.add(run)

    def _destroy_quietly(self) -> None:
        for ref in self.refs:
            try:
                self.driver.destroy(ref)
            except DriverError as exc:
                log.warning("destroying %s failed: %s", ref.id, exc)


def reconcile_fleets_at_boot() -> int:
    """Destroy worker groups left behind by a control plane that died mid-run."""
    settings = get_settings()
    destroyed = 0
    with session_scope() as session:
        rows = session.scalars(select(Run).where(Run.driver_refs_json.isnot(None))).all()
        for run in rows:
            refs = [DriverRef.from_json(doc) for doc in (run.driver_refs_json or [])]
            for ref in refs:
                if ref is None or ref.kind not in ("swarm", "k8s"):
                    continue
                try:
                    get_driver(ref.kind, settings.fleet).destroy(ref)
                    destroyed += 1
                except DriverError as exc:
                    log.warning("could not destroy stray %s %s: %s", ref.kind, ref.id, exc)
            run.driver_refs_json = None
            session.add(run)
    if destroyed:
        log.warning("destroyed %d worker group(s) left behind by the previous control plane", destroyed)
    return destroyed
