"""The fleet: planning a run's workers, leasing them slots, and merging what they report.

A fleet run has the same shape as an in-process one from the outside (a run
row, live statistics, a summary, cache provenance, correlation), and a
different shape inside: the load is generated by N worker containers that
claim slots from this control plane, wait for one shared start instant, run
their share, and post their final report with the raw histograms. This
module owns all of that, adapted from Stoker's lifecycle where the protocol
was proven on real fleets.

The parts, in the order a run meets them:

* :func:`plan` splits the scenario into worker groups (one per engine) and
  each group into per-slot shares of the load.
* :class:`FleetRun` is the per-run supervisor thread: it evicts and reads the
  cache, launches the groups through a driver, watches the leases, releases
  the fleet with T0, handles a stop, notices a worker that stopped heart-
  beating, and finishes the run when every slot is done or lost.
* :func:`claim`, :func:`mark_ready`, :func:`heartbeat` and :func:`final` are
  the request handlers' halves, fenced by lease id so a stale process can
  never speak for a slot somebody else now holds.
* :func:`merge_summaries` turns N worker summaries into one, with the
  percentiles computed once over the merged histograms.
"""

from __future__ import annotations

import asyncio
import json
import logging
import math
import secrets
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import yaml
from sqlalchemy import select

from regulator_agent.histogram import LatencyHistogram, merge_dicts
from regulator_agent.results import merge_intervals
from regulator_agent.scenario import Scenario, load_scenario
from regulator_agent.smartstore import cache_state, delta as cache_delta, evict_all
from regulator_agent.splunk import SplunkClient
from regulator_agent.sut import correlate, marker_prefix_for

from .adapters import hec_config, indexer_settings, scenario_path, target_config
from .config import FleetSettings, ServerConfig, get_settings
from .crypto import mint_run_token
from .db import session_scope
from .drivers import DriverError, DriverRef, ExecutionDriver, WorkerGroup, get_driver
from .models import (
    LEASE_CLAIMED,
    LEASE_DONE,
    LEASE_FREE,
    LEASE_LOST,
    LEASE_READY,
    LEASE_RUNNING,
    LIVE_LEASE_STATES,
    Run,
    Target,
    WorkerLease,
)
from .samples import build_sample, cache_facts as _cache_facts, store_cache_sample, store_sample
from .telemetry import telemetry


def _target_name(session, run: Run) -> Optional[str]:
    target = session.get(Target, run.target_id) if run.target_id else None
    return target.name if target is not None else None

log = logging.getLogger("regulator.server.fleet")

# How far ahead of "all ready" the shared start is set. Long enough for the
# last worker's next heartbeat to carry it, short enough not to matter.
RELEASE_DELAY_S = 4.0
SUPERVISE_TICK_S = 1.0
# After a stop, how long the workers get to hear the command over their
# heartbeats and report before the driver's SIGTERM is used as the fallback.
DRAIN_GRACE_S = 60.0
STATE_PROVISIONING = "provisioning"
STATE_RELEASING = "releasing"
STATE_RUNNING = "running"
STATE_DRAINING = "draining"
STATE_FINISHED = "finished"
PROTOCOL_VERSION = 1


class FleetError(RuntimeError):
    """The fleet could not be planned or launched."""


# ---------------------------------------------------------------------------
# Planning
# ---------------------------------------------------------------------------


@dataclass
class SlotPlan:
    slot: int
    engine: str
    share: Dict[str, Any]


@dataclass
class GroupPlan:
    engine: str
    image: str
    workers: int
    scenario_files: Dict[str, str]
    slots: List[SlotPlan] = field(default_factory=list)


def _scenario_files(directory: Path, scenario: Scenario) -> Dict[str, str]:
    files = {"scenario.yaml": (directory / "scenario.yaml").read_text(encoding="utf-8")}
    if scenario.searches is not None:
        conf = directory / scenario.searches.file
        if conf.is_file():
            files[scenario.searches.file] = conf.read_text(encoding="utf-8")
    return files


def _sub_scenario_yaml(text: str, engine: str) -> str:
    """The scenario with only the personas of one engine, for a mixed run.

    A mixed scenario becomes two worker groups on two images. Each group runs
    the same scenario file minus the other engine's personas, with the
    engine declared so lint agrees, and the same seed so the draws line up.
    """
    document = yaml.safe_load(text) or {}
    personas = []
    for persona in document.get("personas") or []:
        steps = persona.get("steps") or []
        # Filter the steps, not the personas: a persona that mixes engines
        # keeps its share of each, and neither group's copy fails lint for
        # carrying the other engine's steps.
        kept = [step for step in steps if str(step.get("engine", "api")).lower() == engine]
        saved = bool(persona.get("steps_from")) and engine == "api"
        if not kept and not saved and (steps or engine != "api"):
            continue
        copy = dict(persona)
        if steps:
            copy["steps"] = kept
        elif not saved:
            copy.pop("steps", None)
        personas.append(copy)
    document["personas"] = personas
    document["engine"] = engine
    return yaml.safe_dump(document, sort_keys=False)


def _split_evenly(total: int, workers: int) -> List[int]:
    base, remainder = divmod(int(total), workers)
    return [base + (1 if index < remainder else 0) for index in range(workers)]


def _deal(total: int, weights: Dict[str, float]) -> Dict[str, int]:
    """Apportion an integer by weight so the shares add up to the total.

    Largest remainder, so 7 users split evenly become 4 and 3 rather than
    two independently rounded 4s.
    """
    weight_total = sum(weights.values()) or 1.0
    raw = {key: total * weight / weight_total for key, weight in weights.items()}
    shares = {key: int(math.floor(value)) for key, value in raw.items()}
    remainder = int(total) - sum(shares.values())
    for key in sorted(raw, key=lambda k: (raw[k] - shares[k], k), reverse=True)[: max(0, remainder)]:
        shares[key] += 1
    return shares


def plan(run: Run, scenario: Scenario, directory: Path, settings: FleetSettings) -> List[GroupPlan]:
    """Split the run into worker groups and slots.

    One group per engine the scenario uses. Within a group the closed model's
    virtual users are dealt out as evenly as possible; the open model's
    arrival rate is divided; the schedule model's cron steps are dealt out by
    the worker itself from its slot and the worker count. An explicit worker
    count on the run overrides the density defaults.
    """
    files = _scenario_files(directory, scenario)
    engines = sorted({step.engine for step in scenario.steps}) or ["api"]
    load = scenario.load
    model = load.model
    if run.arrival_rate_per_min:
        model = "open"
    elif run.virtual_users or run.pacing_s is not None:
        model = "closed" if model != "schedule" else model

    total_vus = int(run.virtual_users or load.virtual_users or 1)
    total_rate = float(run.arrival_rate_per_min or load.arrival_rate_per_min or 0.0)
    weights = {engine: 0.0 for engine in engines}
    for persona in scenario.personas:
        persona_engines = {step.engine for step in persona.steps} or {"api"}
        for engine in persona_engines:
            weights[engine] = weights.get(engine, 0.0) + float(persona.weight) / max(1, len(persona_engines))
    weight_total = sum(weights.values()) or 1.0

    groups: List[GroupPlan] = []
    next_slot = 0
    vus_by_engine = _deal(total_vus, weights) if len(engines) > 1 else {engines[0]: total_vus}
    workers_by_engine = (
        _deal(int(run.workers), weights) if run.workers and run.workers > 0 and len(engines) > 1 else {}
    )
    for engine in engines:
        density = settings.browser_contexts_per_worker if engine == "browser" else settings.vus_per_worker
        vus = max(1, int(vus_by_engine.get(engine, 0)))
        rate = total_rate if len(engines) == 1 else total_rate * weights[engine] / weight_total
        if run.workers and run.workers > 0:
            workers = int(run.workers) if len(engines) == 1 else max(1, int(workers_by_engine.get(engine, 1)))
        elif model == "closed":
            workers = max(1, math.ceil(vus / density))
        elif model == "open":
            # A worker honestly sustains about one arrival a second per unit
            # of its density, the rule the in-process ceiling applies too.
            workers = max(1, math.ceil(rate / (density * 60.0))) if rate else 1
        else:
            workers = 1
        if model == "closed" and workers > vus:
            # More workers than users would hand every worker one user and
            # run more load than was configured.
            workers = vus
        group = GroupPlan(
            engine=engine,
            image=settings.browser_worker_image if engine == "browser" else settings.worker_image,
            workers=workers,
            scenario_files=(
                files if len(engines) == 1
                else {**files, "scenario.yaml": _sub_scenario_yaml(files["scenario.yaml"], engine)}
            ),
        )
        vu_shares = _split_evenly(vus, workers) if model == "closed" else [0] * workers
        for index in range(workers):
            share: Dict[str, Any] = {"model": model, "engine": engine, "group_slot": index, "group_workers": workers}
            if model == "closed":
                share["virtual_users"] = max(1, vu_shares[index])
            elif model == "open":
                share["arrival_rate_per_min"] = round(rate / workers, 4)
            group.slots.append(SlotPlan(slot=next_slot, engine=engine, share=share))
            next_slot += 1
        groups.append(group)
    return groups


# ---------------------------------------------------------------------------
# Launch
# ---------------------------------------------------------------------------


def public_base_url(settings: ServerConfig, fleet_kind: str) -> str:
    configured = settings.fleet.public_base_url
    if configured:
        return configured.rstrip("/")
    if fleet_kind == "k8s":
        return f"http://regulator.{settings.fleet.k8s_namespace}.svc:8080"
    return "http://regulator:8080"


def launch(run_id: int, driver: Optional[ExecutionDriver] = None, start: bool = True) -> "FleetRun":
    """Plan the run, seed its leases and start its supervisor thread.

    Raises :class:`FleetError` before anything is launched when the plan
    cannot be made; a driver failure after that is recorded on the run. With
    ``start=False`` the caller registers the supervisor first, then starts it.
    """
    settings = get_settings()
    with session_scope() as session:
        run = session.get(Run, run_id)
        if run is None:
            raise FleetError(f"run {run_id} does not exist")
        target = session.get(Target, run.target_id) if run.target_id else None
        if target is None:
            raise FleetError("the target for this run has been deleted")
        directory, _ = scenario_path(run.scenario)
        scenario = load_scenario(directory)
        groups = plan(run, scenario, directory, settings.fleet)
        if driver is None:
            driver = get_driver(run.fleet, settings.fleet)
        if run.fleet == "swarm" and not settings.fleet.swarm_available:
            raise FleetError("the swarm fleet needs PORTAINER_HOST and PORTAINER_TOKEN on the control plane")

        # Seed a lease per slot: the roster the workers claim from.
        for existing in list(run.leases):
            session.delete(existing)
        for group in groups:
            for slot_plan in group.slots:
                session.add(
                    WorkerLease(
                        run_id=run.id,
                        slot=slot_plan.slot,
                        engine=slot_plan.engine,
                        state=LEASE_FREE,
                        share_json={**slot_plan.share, "group": group.engine},
                    )
                )
        run.workers = sum(group.workers for group in groups)
        run.fleet_state = STATE_PROVISIONING
        run.state = "pending"
        run.t0 = None
        session.add(run)
        run_number = run.id

    supervisor = FleetRun(run_number, groups, driver)
    if start:
        supervisor.start()
    return supervisor


# ---------------------------------------------------------------------------
# The request handlers' halves
# ---------------------------------------------------------------------------


def _leases(session, run: Run) -> List[WorkerLease]:
    return list(
        session.scalars(select(WorkerLease).where(WorkerLease.run_id == run.id).order_by(WorkerLease.slot))
    )


def _find(session, run: Run, slot: int) -> Optional[WorkerLease]:
    return session.scalar(select(WorkerLease).where(WorkerLease.run_id == run.id, WorkerLease.slot == slot))


def _holder_ok(lease: Optional[WorkerLease], lease_id: Optional[str]) -> bool:
    return lease is not None and bool(lease_id) and lease.lease_id == lease_id


def _claim_env(run: Run, target: Target, settings: ServerConfig, share: Dict[str, Any]) -> Dict[str, str]:
    """The standalone environment a worker would have had, from the run row.

    The worker parses this with the same code and validations as a standalone
    run, so there is one way for a value to be wrong.
    """
    cfg = target_config(target)
    env: Dict[str, str] = {
        "REG_TARGET_URL": cfg.url,
        "REG_TARGET_VERIFY_TLS": "1" if cfg.verify_tls else "0",
        "REG_TARGET_APP": cfg.app,
        "REG_TARGET_OWNER": cfg.owner,
        "REG_TARGET_API_VERSION": cfg.api_version,
        "REG_LINT_STRICT": "1",
        # The control plane evicts and reads the cache; workers never touch it.
        "REG_EVICT_CACHE": "0",
    }
    if cfg.web_url:
        env["REG_TARGET_WEB_URL"] = cfg.web_url
    if cfg.token:
        env["REG_TARGET_TOKEN"] = cfg.token
    if cfg.username and cfg.password:
        env["REG_TARGET_USERNAME"] = cfg.username
        env["REG_TARGET_PASSWORD"] = cfg.password
    hec = hec_config(settings)
    if hec is not None:
        env["REG_HEC_URL"] = hec.url
        env["REG_HEC_TOKEN"] = hec.token
        env["REG_HEC_VERIFY_TLS"] = "1" if hec.verify_tls else "0"
        env["REG_HEC_SOURCE"] = hec.source
        env["REG_HEC_SOURCETYPE_STEP"] = hec.sourcetype_step
        env["REG_HEC_SOURCETYPE_RUN"] = hec.sourcetype_run
        env["REG_HEC_GZIP"] = "1" if hec.gzip else "0"
        if hec.index:
            env["REG_HEC_INDEX"] = hec.index
    if share.get("model") == "closed" and share.get("virtual_users"):
        env["REG_VUS"] = str(int(share["virtual_users"]))
    if share.get("model") == "open" and share.get("arrival_rate_per_min"):
        env["REG_ARRIVAL_RATE_PER_MIN"] = str(share["arrival_rate_per_min"])
    if run.duration_s:
        env["REG_DURATION_S"] = str(run.duration_s)
    if run.pacing_s is not None:
        env["REG_PACING_S"] = str(run.pacing_s)
    if run.seed:
        env["REG_SEED"] = str(run.seed)
    if run.cold_window_s:
        env["REG_COLD_WINDOW_S"] = str(run.cold_window_s)
    return env


def claim(
    session,
    run: Run,
    holder: str,
    hint_slot: Optional[int],
    files_by_engine: Dict[str, Dict[str, str]],
    engine: Optional[str] = None,
) -> Dict[str, Any]:
    """Issue a lease. Fenced with a fresh lease id every time it changes hands.

    The write is a conditional update on the lease's current state, so two
    workers claiming at the same instant cannot both be told they hold the
    same slot: the second update matches no row and moves on to the next.
    """
    from fastapi import HTTPException
    from sqlalchemy import update

    if run.fleet_state in (STATE_DRAINING, STATE_FINISHED) or run.state in ("completed", "stopped", "aborted", "failed"):
        raise HTTPException(status_code=409, detail="the run is not accepting claims")
    leases = _leases(session, run)
    # Idempotent for a holder that already has a live lease: a retried claim
    # after a dropped response must not take a second slot.
    for lease in leases:
        if lease.holder == holder and lease.state in LIVE_LEASE_STATES:
            lease.last_heartbeat_at = time.time()
            return _claim_response(session, run, lease, files_by_engine)
    claimable = [
        lease for lease in leases
        if lease.state in (LEASE_FREE, LEASE_LOST) and (engine is None or lease.engine == engine)
    ]
    if not claimable:
        wanted = f" for the {engine} engine" if engine else ""
        raise HTTPException(status_code=409, detail=f"no free lease{wanted}: every slot is held")
    ordered = claimable
    if hint_slot is not None:
        ordered = [lease for lease in claimable if lease.slot == hint_slot] + [
            lease for lease in claimable if lease.slot != hint_slot
        ]
    now = time.time()
    for candidate in ordered:
        lease_id = secrets.token_urlsafe(16)
        result = session.execute(
            update(WorkerLease)
            .where(WorkerLease.id == candidate.id, WorkerLease.state.in_((LEASE_FREE, LEASE_LOST)))
            .values(
                lease_id=lease_id,
                holder=holder,
                state=LEASE_CLAIMED,
                claimed_at=now,
                last_heartbeat_at=now,
                restarts=(candidate.restarts or 0) + (1 if candidate.state == LEASE_LOST else 0),
            )
        )
        if result.rowcount == 1:
            session.flush()
            session.refresh(candidate)
            telemetry.lifecycle(
                "worker_claimed", run, _target_name(session, run),
                slot=candidate.slot, worker=holder, engine=candidate.engine, restarts=candidate.restarts,
            )
            return _claim_response(session, run, candidate, files_by_engine)
    raise HTTPException(status_code=409, detail="every free slot was taken by another claim; retry")


def _claim_response(session, run: Run, lease: WorkerLease, files_by_engine: Dict[str, Dict[str, str]]) -> Dict[str, Any]:
    settings = get_settings()
    target = session.get(Target, run.target_id)
    share = dict(lease.share_json or {})
    files = files_by_engine.get(lease.engine) or next(iter(files_by_engine.values()), {})
    return {
        "slot": lease.slot,
        "lease_id": lease.lease_id,
        "total_workers": int(run.workers or 1),
        "engine": lease.engine,
        "run_label": f"r{run.id}" + (f"-{run.label}" if run.label else ""),
        "scenario": {"name": run.scenario, "files": files},
        "env": _claim_env(run, target, settings, share),
        "share": share,
        "heartbeat_s": settings.fleet.heartbeat_s,
        "lease_s": settings.fleet.lease_s,
        "t0": run.t0,
    }


def mark_ready(session, run: Run, slot: int, lease_id: Optional[str]) -> Dict[str, Any]:
    """The worker is warmed up. Returns T0 when the fleet is already released.

    A lease that was marked lost while the worker warmed up is restored here:
    the worker is evidently alive, and a late worker is better in the fleet
    than stranded outside it.
    """
    from fastapi import HTTPException

    lease = _find(session, run, slot)
    if not _holder_ok(lease, lease_id):
        raise HTTPException(status_code=409, detail="lease is not the slot holder (superseded)")
    assert lease is not None
    lease.last_heartbeat_at = time.time()
    if lease.state in (LEASE_CLAIMED, LEASE_READY, LEASE_LOST):
        lease.state = LEASE_READY
    session.add(lease)
    session.flush()
    telemetry.lifecycle("worker_ready", run, _target_name(session, run), slot=lease.slot, worker=lease.holder)
    evaluate_release(session, run)
    return {"t0": run.t0}


def _release_delay() -> float:
    """Long enough for the last ready worker's next heartbeat to carry T0."""
    try:
        heartbeat_s = float(get_settings().fleet.heartbeat_s)
    except Exception:  # noqa: BLE001 - settings are always loadable in a server
        heartbeat_s = 2.0
    return max(RELEASE_DELAY_S, 2.5 * heartbeat_s)


def evaluate_release(session, run: Run, force: bool = False) -> bool:
    """Set T0 once every live lease is ready, or when forced by the timeout."""
    if run.t0 is not None or run.fleet_state not in (STATE_PROVISIONING, None):
        return False
    leases = _leases(session, run)
    ready = [lease for lease in leases if lease.state == LEASE_READY]
    pending = [lease for lease in leases if lease.state in (LEASE_FREE, LEASE_CLAIMED)]
    if not ready:
        return False
    if pending and not force:
        return False
    if pending:
        for lease in pending:
            lease.state = LEASE_LOST
            session.add(lease)
    delay = _release_delay()
    run.t0 = time.time() + delay
    run.fleet_state = STATE_RELEASING
    session.add(run)
    log.info("run %s released: T0 in %.0fs, %d worker(s) ready, %d lost", run.id, delay, len(ready), len(pending))
    telemetry.lifecycle(
        "run_released", run, _target_name(session, run),
        t0=run.t0, ready=len(ready), lost=[lease.slot for lease in pending], forced=bool(force and pending),
    )
    return True


def _with_epoch(run: Run, reply: Dict[str, Any]) -> Dict[str, Any]:
    """Every reply carries the run's current cache epoch, so a worker that
    missed the beat in which it changed still catches up on the next."""
    from .runner import manager

    epochs = manager.epochs_for(run.id)
    if epochs:
        reply["epoch"] = epochs[-1]["epoch"]
        reply["epoch_started_at"] = epochs[-1]["requested_at"]
    return reply


def heartbeat(session, run: Run, slot: int, lease_id: Optional[str], payload: Dict[str, Any]) -> Dict[str, Any]:
    """Renew the lease, keep its live statistics, and answer with a command."""
    return _with_epoch(run, _heartbeat(session, run, slot, lease_id, payload))


def _heartbeat(session, run: Run, slot: int, lease_id: Optional[str], payload: Dict[str, Any]) -> Dict[str, Any]:
    lease = _find(session, run, slot)
    if not _holder_ok(lease, lease_id):
        return {"command": "superseded"}
    assert lease is not None
    now = time.time()
    lease.last_heartbeat_at = now
    stats = payload.get("stats")
    if isinstance(stats, dict):
        lease.stats_json = stats
    interval = payload.get("interval")
    if isinstance(interval, dict) and interval.get("executions") is not None:
        # Handed to the supervisor, which merges every worker's interval into
        # the run's next sample.
        from .runner import manager

        supervisor = manager.fleet_run(run.id)
        if supervisor is not None:
            supervisor.absorb(slot, interval)
    reported = str(payload.get("state") or "")
    if run.fleet_state == STATE_DRAINING or run.state in ("stopped", "aborted", "failed", "completed"):
        session.add(lease)
        return {"command": "stop"}
    if lease.state == LEASE_LOST:
        # It is evidently alive: a heartbeat lost in transit, or a warm-up
        # longer than a lease. Put it back where its own report says it is.
        lease.state = LEASE_READY if reported in ("ready", "running", "finishing") else LEASE_CLAIMED
    if run.t0 is None:
        if lease.state == LEASE_READY:
            # A lease restored to ready through a heartbeat must be able to
            # complete the fleet, not wait for the provisioning timeout.
            evaluate_release(session, run)
        session.add(lease)
        return {"command": "continue"} if run.t0 is None else {"command": "release", "t0": run.t0}
    if reported not in ("running", "finishing") and lease.state != LEASE_DONE:
        # Not yet started: tell it T0 again. Repeating the release until the
        # worker says it is running is what makes a heartbeat lost in
        # transit harmless, whatever state the lease is in.
        session.add(lease)
        return {"command": "release", "t0": run.t0}
    if lease.state in (LEASE_CLAIMED, LEASE_READY):
        lease.state = LEASE_RUNNING
        telemetry.lifecycle("worker_running", run, _target_name(session, run), slot=lease.slot, worker=lease.holder)
    if run.fleet_state == STATE_RELEASING and reported in ("running", "finishing"):
        run.fleet_state = STATE_RUNNING
        run.state = "running"
        run.started_at = run.started_at or run.t0
        session.add(run)
        telemetry.lifecycle("run_started", run, _target_name(session, run), t0=run.t0, workers=run.workers)
    session.add(lease)
    return {"command": "continue"}


def final(session, run: Run, slot: int, lease_id: Optional[str], summary: Dict[str, Any], log_tail: List[str]) -> None:
    """Record a worker's final report. A superseded worker's report is ignored."""
    lease = _find(session, run, slot)
    if lease is None:
        return
    if lease_id and lease.lease_id != lease_id:
        log.info("run %s slot %s: final from a superseded lease ignored", run.id, slot)
        return
    if lease.state != LEASE_DONE:
        lease.summary_json = summary
        lease.log_tail_json = list(log_tail or [])[-200:]
        lease.state = LEASE_DONE
        lease.last_heartbeat_at = time.time()
        session.add(lease)
        stats = summary.get("stats") if isinstance(summary, dict) else {}
        telemetry.lifecycle(
            "worker_done", run, _target_name(session, run), slot=slot, worker=lease.holder,
            outcome=summary.get("outcome") if isinstance(summary, dict) else None,
            valid=summary.get("valid") if isinstance(summary, dict) else None,
            executions=(stats or {}).get("executions"), errors=(stats or {}).get("errors"),
        )


# ---------------------------------------------------------------------------
# Merging
# ---------------------------------------------------------------------------


def _hist(documents: Sequence[Optional[Dict[str, Any]]]) -> LatencyHistogram:
    return merge_dicts([doc for doc in documents if isinstance(doc, dict)])


def summary_problem(summary: Any) -> Optional[str]:
    """Why a worker's summary cannot be merged, or None when it can.

    A worker on a different build can ship histograms this build cannot
    read; a token holder can ship anything at all. One bad document must
    cost its own slot, never every other worker's data.
    """
    if not isinstance(summary, dict):
        return "the final report is not an object"
    try:
        merge_summaries("check", "", [summary], [])
    except Exception as exc:  # noqa: BLE001 - any failure means "do not merge this one"
        return f"unreadable final report: {str(exc)[:160]}"
    return None


def merge_summaries(run_label: str, scenario: str, summaries: Sequence[Dict[str, Any]], lost_slots: Sequence[int]) -> Dict[str, Any]:
    """One summary from many, with the percentiles computed over the merged histograms.

    Counts add. Histograms add. Peaks add (an upper bound on the fleet's true
    peak, stated as such). Percentiles are never averaged: that was the whole
    reason the workers ship buckets rather than numbers.
    """
    summaries = [s for s in summaries if isinstance(s, dict)]
    stats_list = [s.get("stats") or {} for s in summaries]
    hists = [st.get("histograms") or {} for st in stats_list]

    def total(key: str) -> int:
        return int(sum(int(st.get(key) or 0) for st in stats_list))

    started = min((float(s.get("started_at") or 0) for s in summaries if s.get("started_at")), default=time.time())
    ended = max((float(s.get("ended_at") or 0) for s in summaries if s.get("ended_at")), default=time.time())
    duration = max(0.0, ended - started)
    executions = total("executions")
    errors = total("errors")

    errors_by_class: Dict[str, int] = {}
    for st in stats_list:
        for key, value in (st.get("errors_by_class") or {}).items():
            errors_by_class[key] = errors_by_class.get(key, 0) + int(value or 0)

    latency = _hist([h.get("latency") for h in hists])
    failure = _hist([h.get("failure_latency") for h in hists])
    queued = _hist([h.get("queued") for h in hists])
    loop_lag = _hist([h.get("loop_lag") for h in hists])
    drift = _hist([h.get("drift") for h in hists])

    # Steps, merged by id.
    merged_steps: Dict[str, Dict[str, Any]] = {}
    step_hists: Dict[str, List[Dict[str, Any]]] = {}
    for st, h in zip(stats_list, hists):
        for step in st.get("steps") or []:
            sid = str(step.get("step_id"))
            entry = merged_steps.setdefault(
                sid,
                {"step_id": sid, "class": step.get("class", "unclassified"), "executions": 0, "successes": 0,
                 "partial": 0, "errors": 0, "errors_by_class": {}, "scan_count_total": 0,
                 "result_count_total": 0, "_run_duration_total_s": 0.0},
            )
            for key in ("executions", "successes", "partial", "errors", "scan_count_total", "result_count_total"):
                entry[key] += int(step.get(key) or 0)
            for key, value in (step.get("errors_by_class") or {}).items():
                entry["errors_by_class"][key] = entry["errors_by_class"].get(key, 0) + int(value or 0)
            # The per-search mean carries the duration total back out.
            mean_eps = step.get("mean_events_per_s")
            if mean_eps and step.get("scan_count_total"):
                entry["_run_duration_total_s"] += float(step["scan_count_total"]) / float(mean_eps)
            step_hists.setdefault(sid, []).append((h.get("steps") or {}).get(sid) or {})
    # Cache epochs, merged by epoch number across the workers.
    epoch_hists: Dict[str, List[Dict[str, Any]]] = {}
    epoch_execs: Dict[str, int] = {}
    for st, h in zip(stats_list, hists):
        for key, doc in (h.get("epochs") or {}).items():
            epoch_hists.setdefault(str(key), []).append(doc)
        for epoch in st.get("epochs") or []:
            key = str(epoch.get("epoch"))
            epoch_execs[key] = epoch_execs.get(key, 0) + int(epoch.get("executions") or 0)
    epochs_out = [
        {"epoch": int(key), "executions": epoch_execs.get(key, 0), "latency": _hist(docs).summary()}
        for key, docs in sorted(epoch_hists.items(), key=lambda kv: int(kv[0]))
    ]

    steps_out: List[Dict[str, Any]] = []
    for sid, entry in merged_steps.items():
        parts = step_hists.get(sid, [])
        entry["latency"] = _hist([p.get("latency") for p in parts]).summary()
        cold = _hist([p.get("latency_cold") for p in parts])
        warm = _hist([p.get("latency_warm") for p in parts])
        entry["cold"] = cold.summary() if len(cold) else None
        entry["warm"] = warm.summary() if len(warm) else None
        entry["failure_latency"] = _hist([p.get("failure_latency") for p in parts]).summary()
        entry["service_time"] = _hist([p.get("service_time") for p in parts]).summary()
        entry["dispatch"] = _hist([p.get("dispatch") for p in parts]).summary()
        entry["ttfr"] = _hist([p.get("ttfr") for p in parts]).summary()
        entry["error_rate_pct"] = round(100.0 * entry["errors"] / entry["executions"], 3) if entry["executions"] else 0.0
        entry["scan_count_per_search"] = (
            round(entry["scan_count_total"] / entry["successes"], 1) if entry["successes"] else None
        )
        duration_total = entry.pop("_run_duration_total_s")
        entry["mean_events_per_s"] = round(entry["scan_count_total"] / duration_total, 1) if duration_total else None
        steps_out.append(entry)

    job_executions = total("job_executions") or sum(
        int((st.get("queueing") or {}).get("job_executions") or 0) for st in stats_list
    )
    searches_queued = sum(int((st.get("queueing") or {}).get("searches_queued") or 0) for st in stats_list)
    peak_in_flight = sum(int(st.get("peak_in_flight") or 0) for st in stats_list)
    max_loop_lag = max((float((st.get("generator") or {}).get("max_loop_lag_ms") or 0) for st in stats_list), default=0.0)
    max_debt = max((float((st.get("generator") or {}).get("max_schedule_debt_ms") or 0) for st in stats_list), default=0.0)

    stats = {
        "run_id": run_label,
        "slot": 0,
        "elapsed_s": round(duration, 2),
        "executions": executions,
        "successes": executions - errors,
        "iterations_completed": total("iterations_completed"),
        "errors": errors,
        "error_rate_pct": round(100.0 * errors / executions, 3) if executions else 0.0,
        "errors_by_class": errors_by_class,
        "epochs": epochs_out,
        "partial": total("partial"),
        "abandoned": total("abandoned"),
        "in_flight": 0,
        # A sum of per-worker peaks: an upper bound on the fleet's true peak,
        # since the workers' peaks need not have coincided.
        "peak_in_flight": peak_in_flight,
        "peak_in_flight_note": "sum of the workers' peaks, an upper bound",
        "throughput_per_s": round(executions / duration, 2) if duration > 0 else 0.0,
        "latency": latency.summary(),
        "failure_latency": failure.summary(),
        "queueing": {
            "searches_queued": searches_queued,
            "job_executions": job_executions,
            "queued_pct": round(100.0 * searches_queued / job_executions, 2) if job_executions else 0.0,
            "queued_ms": queued.summary(),
        },
        "generator": {
            "max_loop_lag_ms": round(max_loop_lag, 1),
            "loop_lag_p95_ms": round(loop_lag.percentile_ms(95), 1) if len(loop_lag) else 0.0,
            "max_schedule_debt_ms": round(max_debt, 1),
            "schedule_debt_p95_ms": round(drift.percentile_ms(95), 1) if len(drift) else 0.0,
            "max_drift_ms": round(max_debt, 1),
        },
        "steps": steps_out,
        "arrivals_missed": total("arrivals_missed"),
        "arrivals_shed": total("arrivals_shed"),
        "arrivals_skipped": total("arrivals_skipped"),
        "workers": len(summaries),
    }
    first = summaries[0] if summaries else {}
    target = (first.get("stats") or {}).get("target")
    if target:
        stats["target"] = target

    outcomes = [str(s.get("outcome") or "failed") for s in summaries]
    if "failed" in outcomes:
        outcome = "failed"
    elif "aborted" in outcomes:
        outcome = "aborted"
    elif "stopped" in outcomes:
        outcome = "stopped"
    else:
        outcome = "completed"
    reasons = [str(s.get("invalid_reason")) for s in summaries if s.get("invalid_reason")]
    valid = all(bool(s.get("valid")) for s in summaries) and not lost_slots and bool(summaries)
    if lost_slots:
        reasons.append(
            f"{len(lost_slots)} worker(s) were lost (slots {', '.join(str(s) for s in lost_slots)}): "
            "their share of the load was never applied, so this is not the configured workload"
        )
    if not summaries:
        reasons.append("no worker reported a result")

    configured = dict(first.get("configured_load") or {})
    configured["workers"] = len(summaries) + len(lost_slots)
    per_worker = [s.get("configured_load") or {} for s in summaries]
    if configured.get("model") == "closed":
        configured["virtual_users"] = sum(int(p.get("virtual_users") or 0) for p in per_worker)
    elif configured.get("model") == "open":
        configured["arrival_rate_per_min"] = round(sum(float(p.get("arrival_rate_per_min") or 0) for p in per_worker), 3)
    configured.pop("slot", None)

    return {
        "run_id": run_label,
        "slot": 0,
        "scenario": scenario,
        "outcome": outcome,
        "valid": valid,
        "invalid_reason": "; ".join(reasons) or None,
        "started_at": started,
        "ended_at": ended,
        "duration_s": round(duration, 3),
        "target_url": first.get("target_url"),
        "self_instrumented": any(bool(s.get("self_instrumented")) for s in summaries),
        "co_corrected": all(bool(s.get("co_corrected")) for s in summaries) if summaries else False,
        "load_model": first.get("load_model"),
        "peak_virtual_users": sum(int(s.get("peak_virtual_users") or 0) for s in summaries),
        "stats": stats,
        "cache": None,
        "sut": None,
        "abort_reason": next((s.get("abort_reason") for s in summaries if s.get("abort_reason")), None),
        "scenario_seed": first.get("scenario_seed", 0),
        "effective_seed": first.get("effective_seed", first.get("scenario_seed", 0)),
        "scenario_digest": first.get("scenario_digest"),
        "configured_load": configured,
        "agent_version": first.get("agent_version", ""),
        "workers": [
            {
                "slot": int((s.get("stats") or {}).get("slot") or s.get("slot") or 0),
                "outcome": s.get("outcome"),
                "valid": s.get("valid"),
                "executions": int((s.get("stats") or {}).get("executions") or 0),
                "errors": int((s.get("stats") or {}).get("errors") or 0),
                "p95_ms": ((s.get("stats") or {}).get("latency") or {}).get("p95_ms"),
            }
            for s in summaries
        ] + [{"slot": slot, "outcome": "lost", "valid": False, "executions": 0, "errors": 0, "p95_ms": None} for slot in lost_slots],
    }


def live_snapshot(run: Run, leases: Sequence[WorkerLease]) -> Dict[str, Any]:
    """A fleet's live aggregate from its workers' last heartbeats.

    Counts add; percentiles are those of the largest contributor, labelled as
    such, because a heartbeat carries summaries rather than buckets and the
    honest merge waits for the final reports.
    """
    stats_list = [lease.stats_json for lease in leases if isinstance(lease.stats_json, dict)]
    executions = sum(int(st.get("executions") or 0) for st in stats_list)
    errors = sum(int(st.get("errors") or 0) for st in stats_list)
    biggest = max(stats_list, key=lambda st: int(st.get("executions") or 0), default={})
    elapsed = max((float(st.get("elapsed_s") or 0) for st in stats_list), default=0.0)
    return {
        "run_id": f"r{run.id}",
        "elapsed_s": round(elapsed, 2),
        "executions": executions,
        "errors": errors,
        "error_rate_pct": round(100.0 * errors / executions, 3) if executions else 0.0,
        "in_flight": sum(int(st.get("in_flight") or 0) for st in stats_list),
        "peak_in_flight": sum(int(st.get("peak_in_flight") or 0) for st in stats_list),
        "throughput_per_s": round(sum(float(st.get("throughput_per_s") or 0) for st in stats_list), 2),
        "latency": biggest.get("latency") or LatencyHistogram().summary(),
        "latency_note": "live percentiles are the busiest worker's; the merged figures arrive with the final reports",
        "queueing": {
            "searches_queued": sum(int((st.get("queueing") or {}).get("searches_queued") or 0) for st in stats_list),
            "queued_pct": (biggest.get("queueing") or {}).get("queued_pct", 0.0),
            "queued_ms": (biggest.get("queueing") or {}).get("queued_ms") or LatencyHistogram().summary(),
        },
        "generator": biggest.get("generator") or {},
        "steps": [],
        "workers": [
            {
                "slot": lease.slot,
                "engine": lease.engine,
                "state": lease.state,
                "holder": lease.holder,
                "executions": int((lease.stats_json or {}).get("executions") or 0),
                "errors": int((lease.stats_json or {}).get("errors") or 0),
                "p95_ms": ((lease.stats_json or {}).get("latency") or {}).get("p95_ms"),
                "last_heartbeat_at": lease.last_heartbeat_at,
                "restarts": lease.restarts,
            }
            for lease in leases
        ],
        "fleet_state": run.fleet_state,
        "t0": run.t0,
    }


# ---------------------------------------------------------------------------
# The per-run supervisor
# ---------------------------------------------------------------------------


class FleetRun(threading.Thread):
    """One thread per fleet run: launch, watch, release, finish."""

    def __init__(self, run_id: int, groups: List[GroupPlan], driver: ExecutionDriver) -> None:
        super().__init__(name=f"regulator-fleet-{run_id}", daemon=True)
        self.run_id = run_id
        self.groups = groups
        self.driver = driver
        self.files_by_engine: Dict[str, Dict[str, str]] = {g.engine: g.scenario_files for g in groups}
        self.refs: List[DriverRef] = []
        self.stop_requested = False
        self._stopped_driver = False
        self._target_name: Optional[str] = None
        # Interval documents from the workers' heartbeats, per slot, waiting
        # for the next sample to merge them.
        self._intervals: Dict[int, List[Dict[str, Any]]] = {}
        self._interval_lock = threading.Lock()

    def absorb(self, slot: int, interval: Dict[str, Any]) -> None:
        """Keep a worker's interval until the next sample merges it."""
        with self._interval_lock:
            self._intervals.setdefault(int(slot), []).append(interval)

    def _take_intervals(self) -> Dict[int, List[Dict[str, Any]]]:
        with self._interval_lock:
            pending, self._intervals = self._intervals, {}
        return pending

    def request_stop(self) -> None:
        self.stop_requested = True
        with session_scope() as session:
            run = session.get(Run, self.run_id)
            if run is not None and run.fleet_state not in (STATE_FINISHED,):
                run.fleet_state = STATE_DRAINING
                session.add(run)

    # ------------------------------------------------------------------

    def run(self) -> None:  # noqa: D102 - Thread API
        try:
            asyncio.run(self._supervise())
        except Exception as exc:  # noqa: BLE001 - recorded on the run, never lost
            log.exception("fleet run %s failed", self.run_id)
            self._finish_failed(f"the fleet supervisor failed: {exc}")
        finally:
            self._destroy_quietly()
            from .runner import manager

            manager.forget(self.run_id)

    async def _supervise(self) -> None:
        settings = get_settings()
        with session_scope() as session:
            run = session.get(Run, self.run_id)
            target = session.get(Target, run.target_id)
            self._target_name = target.name
            target_id = target.id
            cfg = target_config(target)
            where = indexer_settings(target)
            evict_indexes = (run.evict_cache_indexes or "").split(",") if run.evict_cache_indexes else []
            evict = bool(run.evict_cache)
            run_evict_every = float(run.evict_every_s or 0)
            corpus_index = None
            duration = float(run.duration_s or 0)
            label = f"r{run.id}" + (f"-{run.label}" if run.label else "")
        try:
            directory, _ = scenario_path(self._scenario_name())
            scenario = load_scenario(directory)
            corpus_index = scenario.corpus.index
            if not duration:
                duration = float(scenario.load.duration_s or 0)
        except Exception:  # noqa: BLE001 - the plan already loaded it once
            pass

        client = SplunkClient(cfg)
        await client.start()
        eviction = None
        before = None
        # A ramp-only scenario has no declared duration; the deadlines then
        # cover the longest run this control plane allows rather than
        # cutting a healthy fleet off after five minutes.
        deadline_basis = duration or float(settings.max_run_duration_s)
        try:
            if evict:
                indexes = None if "*" in evict_indexes else (evict_indexes or ([corpus_index] if corpus_index else None))
                eviction = await evict_all(client, indexes=indexes, **where)
            before = await cache_state(client, **where)
            with session_scope() as session:
                run = session.get(Run, self.run_id)
                store_cache_sample(session, target_id, self.run_id, "before", before.to_dict())
            if eviction is not None:
                telemetry.lifecycle("cache_evicted", run, self._target_name, **{k: v for k, v in eviction.to_dict().items() if k != "errors"})
            telemetry.lifecycle("cache_before", run, self._target_name, **_cache_facts(before.to_dict()))

            # Launch every group. The bootstrap is the same for all of them;
            # the token rides as a secret the driver projects, never as
            # environment.
            token = mint_run_token(self.run_id)
            base_url = public_base_url(settings, self.driver.kind if self.driver.kind != "fake" else "swarm")
            slot_base = 0
            for group in self.groups:
                worker_group = WorkerGroup(
                    run_id=self.run_id,
                    group=group.engine,
                    image=group.image,
                    workers=group.workers,
                    env={
                        "REG_RUN_ID": str(self.run_id),
                        "REG_CONTROL_URL": base_url,
                        "REG_LOG_LEVEL": "INFO",
                    },
                    secrets={"REG_RUN_JWT": token},
                    labels={"regulator.scenario": self._scenario_name()},
                    stop_grace_s=90,
                    options={"slot_base": slot_base, "active_deadline_s": int(deadline_basis + 600)},
                )
                slot_base += group.workers
                try:
                    ref = self.driver.create(worker_group)
                except DriverError as exc:
                    raise FleetError(f"could not launch the {group.engine} workers: {exc}") from exc
                self.refs.append(ref)
                # Persisted as each group is created, so a control plane that
                # dies between two groups leaves nothing the boot sweep
                # cannot find.
                with session_scope() as session:
                    run = session.get(Run, self.run_id)
                    run.driver_refs_json = [r.to_json() for r in self.refs]
                    session.add(run)

            evictor: Optional[asyncio.Task[None]] = None
            if run_evict_every:
                periodic_indexes = None if "*" in evict_indexes else (evict_indexes or ([corpus_index] if corpus_index else None))
                evictor = asyncio.create_task(self._evict_loop(client, where, periodic_indexes, run_evict_every, target_id))
            try:
                await self._watch(settings, deadline_basis)
            finally:
                if evictor is not None:
                    evictor.cancel()
                    try:
                        await evictor
                    except (asyncio.CancelledError, Exception):  # noqa: BLE001
                        pass

            # Every slot is done or lost: merge, then the cluster's own view.
            # A report this build cannot read costs its own slot only.
            with session_scope() as session:
                run = session.get(Run, self.run_id)
                leases = _leases(session, run)
                summaries = []
                lost = []
                lost_reasons: List[str] = []
                for lease in leases:
                    if lease.state == LEASE_DONE and lease.summary_json:
                        problem = summary_problem(lease.summary_json)
                        if problem is None:
                            summaries.append(lease.summary_json)
                            continue
                        log.warning("run %s slot %s: %s", self.run_id, lease.slot, problem)
                        lost_reasons.append(f"slot {lease.slot}: {problem}")
                        lease.state = LEASE_LOST
                        session.add(lease)
                    if lease.state == LEASE_LOST:
                        lost.append(lease.slot)
                scenario_name = run.scenario
            merged = merge_summaries(label, scenario_name, summaries, lost)
            if lost_reasons:
                merged["invalid_reason"] = "; ".join(filter(None, [merged.get("invalid_reason"), *lost_reasons]))
            if before is not None and before.available:
                after = await cache_state(client, **where)
                merged["cache"] = {"before": before.to_dict(), "after": after.to_dict(), "delta": cache_delta(before, after).to_dict()}
                if eviction is not None:
                    merged["cache"]["eviction"] = eviction.to_dict()
                with session_scope() as session:
                    store_cache_sample(session, target_id, self.run_id, "after", after.to_dict(), {"delta": merged["cache"]["delta"]})
                telemetry.lifecycle("cache_after", run, self._target_name, **_cache_facts(after.to_dict()), delta=merged["cache"]["delta"])
            elif before is not None:
                merged["cache"] = {"available": False, "reason": before.reason}
            if merged.get("started_at") and merged.get("ended_at") and summaries:
                try:
                    merged["sut"] = await correlate(client, merged["started_at"], merged["ended_at"], marker_prefix_for(label))
                except Exception as exc:  # noqa: BLE001 - correlation never fails a run
                    log.warning("correlation failed for run %s: %s", self.run_id, exc)
            from .runner import manager as _manager

            epochs = _manager.epochs_for(self.run_id, forget=True)
            if epochs:
                merged["cache"] = {**(merged.get("cache") or {}), "epochs": epochs}
            with session_scope() as session:
                run = session.get(Run, self.run_id)
                run.summary_json = merged
                run.stats_json = merged.get("stats")
                if summaries:
                    run.state = merged["outcome"]
                else:
                    # Nothing came back: a stop before any worker reported is
                    # a stopped run, anything else is a failed one.
                    run.state = "stopped" if self.stop_requested else "failed"
                if not summaries and not run.error and not self.stop_requested:
                    run.error = merged.get("invalid_reason") or "no worker reported a result"
                run.ended_at = time.time()
                run.fleet_state = STATE_FINISHED
                session.add(run)
                final_state = run.state
            if isinstance(merged.get("sut"), dict):
                telemetry.lifecycle("correlation", run, self._target_name, findings=merged["sut"].get("findings"), probes=sorted((merged["sut"].get("probes") or {}).keys()))
            stats = merged.get("stats") or {}
            telemetry.lifecycle(
                f"run_{final_state}", run, self._target_name, outcome=final_state, valid=merged.get("valid"),
                invalid_reason=merged.get("invalid_reason"), executions=stats.get("executions"), errors=stats.get("errors"),
                p95_ms=(stats.get("latency") or {}).get("p95_ms"), error_rate_pct=stats.get("error_rate_pct"),
                workers=stats.get("workers"), lost=lost,
            )
            telemetry.run_final(run, merged, scope="fleet", target_name=self._target_name)
        finally:
            await client.close()

    async def _evict_loop(self, client: SplunkClient, where: Dict[str, Any], indexes, every_s: float, target_id: int) -> None:
        """The fleet's periodic eviction: the clock starts at T0, and every
        eviction is an epoch every worker hears about on its next heartbeat."""
        from .cachelock import evict_lock
        from .runner import manager

        t0: Optional[float] = None
        try:
            while t0 is None:
                await asyncio.sleep(1.0)
                with session_scope() as session:
                    run = session.get(Run, self.run_id)
                    t0 = run.t0 if run is not None else None
                    if run is None or run.fleet_state in (STATE_DRAINING, STATE_FINISHED):
                        return
            due = t0 + every_s
            while True:
                await asyncio.sleep(max(0.2, due - time.time()))
                started = time.time()
                try:
                    async with evict_lock(target_id):
                        result = await asyncio.wait_for(evict_all(client, indexes=indexes, **where), timeout=min(every_s, 600.0))
                    outcome = result.to_dict()
                except asyncio.TimeoutError:
                    outcome = {"attempted": 0, "evicted": 0, "confirmed": 0, "failed": 0, "bytes_evicted": 0, "status": "timeout"}
                except Exception as exc:  # noqa: BLE001
                    outcome = {"attempted": 0, "evicted": 0, "confirmed": 0, "failed": 0, "bytes_evicted": 0, "status": f"failed: {str(exc)[:120]}"}
                duration = round(time.time() - started, 1)
                epoch = manager.mark_cache_epoch(self.run_id, {**outcome, "duration_s": duration}, source="timer")
                if epoch is not None and duration > every_s:
                    epoch["note"] = f"the eviction took {duration}s, longer than the {every_s:.0f}s interval: epochs are irregular"
                try:
                    after = await cache_state(client, **where)
                    with session_scope() as session:
                        run = session.get(Run, self.run_id)
                        store_cache_sample(session, target_id, self.run_id, "epoch", after.to_dict(), {"epoch": epoch})
                    telemetry.lifecycle("cache_epoch", run, self._target_name, **(epoch or {}), **_cache_facts(after.to_dict()))
                except Exception:  # noqa: BLE001
                    log.debug("cache reading after the periodic eviction failed", exc_info=True)
                due = max(time.time(), due + every_s)
        except asyncio.CancelledError:
            return

    def _driver_notes(self) -> List[str]:
        """What the driver itself says about the workers, for the operator."""
        notes: List[str] = []
        for ref in self.refs:
            try:
                status = self.driver.status(ref)
            except DriverError as exc:
                notes.append(f"{ref.group}: status unavailable ({exc})")
                continue
            notes.append(f"{ref.group}: {status.running} of {status.desired} running")
            for task in status.tasks:
                message = task.get("message") or task.get("state")
                if message and str(message).lower() not in ("started", "running"):
                    notes.append(f"{ref.group}: {message}")
        return notes[:12]

    async def _watch(self, settings: ServerConfig, duration: float) -> None:
        """Until every lease is done or lost.

        Three clocks: a lease lapses when its heartbeats stop (a claimed
        lease still warming up gets the provisioning window instead, because
        an engine start and a validation can outlast a lease); the run is
        released or given up at the provisioning deadline; and a wall-clock
        ceiling that depends on nothing else, so no state, not even a stop
        before the first claim, can leave this loop running for ever.
        """
        started = time.time()
        provision_deadline = started + settings.fleet.provision_timeout_s
        lease_s = settings.fleet.lease_s
        hard_deadline: Optional[float] = None
        ceiling = started + settings.fleet.provision_timeout_s + float(duration or settings.max_run_duration_s) + 600.0
        drain_started: Optional[float] = None
        last_persist = 0.0
        sample_every = max(1.0, float(getattr(settings, "sample_interval_s", 5.0)))
        last_sample = started
        while True:
            await asyncio.sleep(SUPERVISE_TICK_S)
            shipped: List[Tuple[Dict[str, Any], Optional[int]]] = []
            events: List[Tuple[str, Dict[str, Any]]] = []
            with session_scope() as session:
                run = session.get(Run, self.run_id)
                leases = _leases(session, run)
                now = time.time()
                draining = run.fleet_state == STATE_DRAINING

                # A worker that stopped heartbeating loses its lease.
                for lease in leases:
                    if lease.state not in LIVE_LEASE_STATES or not lease.last_heartbeat_at:
                        continue
                    warming_up = lease.state == LEASE_CLAIMED and now <= provision_deadline and not draining
                    allowance = max(lease_s, settings.fleet.provision_timeout_s) if warming_up else lease_s
                    silent = now - lease.last_heartbeat_at
                    if silent > allowance:
                        log.warning("run %s slot %s lost: no heartbeat for %.0fs", run.id, lease.slot, silent)
                        lease.state = LEASE_LOST
                        session.add(lease)
                        events.append(("worker_lost", {"slot": lease.slot, "worker": lease.holder, "silent_s": round(silent, 1)}))

                # The time series: every worker's intervals since the last
                # sample, merged (percentiles over merged buckets) into one
                # aggregate row, plus a row per slot.
                if now - last_sample >= sample_every:
                    pending = self._take_intervals()
                    if pending or any(lease.stats_json for lease in leases):
                        aggregate = live_snapshot(run, leases)
                        sample = build_sample(merge_intervals([d for docs in pending.values() for d in docs]), aggregate, now)
                        store_sample(session, run.id, sample)
                        shipped.append((sample, None))
                        for lease in leases:
                            docs = pending.get(lease.slot)
                            if docs:
                                slot_sample = build_sample(merge_intervals(docs), lease.stats_json or {}, now, slot=lease.slot)
                                store_sample(session, run.id, slot_sample)
                                shipped.append((slot_sample, lease.slot))
                    last_sample = now

                if run.t0 is None and run.fleet_state == STATE_PROVISIONING and now > provision_deadline:
                    if not evaluate_release(session, run, force=True):
                        for lease in leases:
                            if lease.state in (LEASE_FREE, LEASE_CLAIMED):
                                lease.state = LEASE_LOST
                                session.add(lease)
                                events.append(("worker_lost", {"slot": lease.slot, "worker": lease.holder, "reason": "provisioning timeout"}))
                        notes = self._driver_notes()
                        run.error = "no worker became ready within the provisioning timeout" + (
                            ". The driver reports: " + "; ".join(notes) if notes else ""
                        )
                        run.fleet_state = STATE_DRAINING
                        draining = True
                        session.add(run)

                if draining:
                    drain_started = drain_started or now
                    # Nobody will claim a free slot now; a claimed or ready
                    # worker hears "stop" on its next heartbeat and reports.
                    for lease in leases:
                        if lease.state == LEASE_FREE:
                            lease.state = LEASE_LOST
                            session.add(lease)

                if run.t0 is not None and hard_deadline is None:
                    hard_deadline = run.t0 + float(duration or settings.max_run_duration_s) + 300.0

                # The live aggregate is persisted so a restart, or a page
                # opened later, still has what the fleet reported so far.
                if now - last_persist >= 5.0 and any(lease.stats_json for lease in leases):
                    run.stats_json = live_snapshot(run, leases)
                    session.add(run)
                    last_persist = now

                states = [lease.state for lease in leases]
                finished = all(state in (LEASE_DONE, LEASE_LOST) for state in states)
                timed_out = (hard_deadline is not None and now > hard_deadline) or now > ceiling
                if timed_out and not finished:
                    for lease in leases:
                        if lease.state not in (LEASE_DONE,):
                            lease.state = LEASE_LOST
                            session.add(lease)
                            events.append(("worker_lost", {"slot": lease.slot, "worker": lease.holder, "reason": "deadline"}))
                    if not run.error:
                        run.error = "the run outlived its deadline; workers still running were declared lost"
                        session.add(run)
            # Outside the session: telemetry is fire and forget, and the run
            # row's attributes survive the session's close.
            for sample, slot in shipped:
                telemetry.sample(run, sample, self._target_name, slot=slot)
            for kind, detail in events:
                telemetry.lifecycle(kind, run, self._target_name, **detail)
            if finished or timed_out:
                return
            with session_scope() as session:
                run = session.get(Run, self.run_id)
                draining = run.fleet_state == STATE_DRAINING
                # The driver's own stop (SIGTERM) is the fallback for a worker
                # that never heard the command over its heartbeat. Workers
                # that did hear it are reporting and exiting on their own.
                if draining and not self._stopped_driver and drain_started and now - drain_started > DRAIN_GRACE_S:
                    self._stopped_driver = True
                    for ref in self.refs:
                        try:
                            self.driver.stop(ref, grace_s=90)
                        except DriverError as exc:
                            log.warning("stopping %s failed: %s", ref.id, exc)

    def _scenario_name(self) -> str:
        with session_scope() as session:
            run = session.get(Run, self.run_id)
            return run.scenario if run else ""

    def _finish_failed(self, error: str) -> None:
        with session_scope() as session:
            run = session.get(Run, self.run_id)
            if run is None:
                return
            run.state = "failed"
            run.error = error
            run.ended_at = time.time()
            run.fleet_state = STATE_FINISHED
            session.add(run)

    def _destroy_quietly(self) -> None:
        remaining: List[DriverRef] = []
        for ref in self.refs:
            try:
                self.driver.destroy(ref)
            except DriverError as exc:
                log.warning("destroying %s failed: %s", ref.id, exc)
                remaining.append(ref)
        # A finished run holds no refs, so the boot sweep has nothing to do
        # for it; only what could not be removed stays recorded.
        with session_scope() as session:
            run = session.get(Run, self.run_id)
            if run is not None:
                run.driver_refs_json = [r.to_json() for r in remaining] or None
                session.add(run)


def reconcile_fleets_at_boot() -> int:
    """Destroy worker groups left behind by a control plane that died mid-run.

    Only runs that were still in flight are swept: a finished run's refs are
    cleared when it finishes, and sweeping history against a slow Portainer
    at every boot is how a control plane fails its own readiness probe.
    """
    settings = get_settings()
    swept = 0
    with session_scope() as session:
        rows = session.scalars(
            select(Run).where(Run.driver_refs_json.isnot(None), Run.state.in_(("pending", "running")))
        ).all()
        for run in rows:
            refs = [DriverRef.from_json(doc) for doc in (run.driver_refs_json or [])]
            for ref in refs:
                if ref is None or ref.kind not in ("swarm", "k8s"):
                    continue
                try:
                    get_driver(ref.kind, settings.fleet).destroy(ref)
                    swept += 1
                except DriverError as exc:
                    log.warning("could not destroy stray %s %s: %s", ref.kind, ref.id, exc)
            run.driver_refs_json = None
            session.add(run)
    if swept:
        log.warning("swept %d worker group(s) left behind by the previous control plane", swept)
    return swept
